[package]
name = "lattice"
version = "0.1.0"
authors = ["Hilmar GÃºstafsson <LiHRaM@users.noreply.github.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"